### ISSUE TITLE
I made Piping a VM List available for HVBackupLaunch.ps1

### ISSUE THREAD

**Issue by Jimshark** [nelsh/HVbackupLaunch#1]
Usage:
"get-vm | select Name | "HVBackupLaunch.ps1" -Path %BCKPATH%" -verbose"
Also Error trap, Total backup time, Verbose and minor modifications...
Tested OK on a Hyper-v 2012R2 cluster with HVBackup 101
Thanks for your job and happy to collaborate. :-)
[HVbackupLaunch.zip](https://github.com/nelsh/HVbackupLaunch/files/209699/HVbackupLaunch.zip)

**Comment by nelsh** [comment]
Good job. Thanks.

**Comment by donatofurio** [comment]
HI, when i launch the script i have always this error...any ideas?

PS C:\HVBackup> .\HVbackupLaunch.ps1

Cmdlet HVbackupLaunch.ps1 nella posizione 1 della pipeline dei comandi
Specificare i valori per i seguenti parametri:
VMList[0]: server01
VMList[1]:
Path[0]: d:\
Path[1]:

```
Directory: C:\HVBackup
```

Mode                LastWriteTime     Length Name

---

-a---        03/05/2016     14.02          0 report.txt
INFO    Start
INFO    Backup server01. Run: HyperVBackup.exe --compressionlevel 2 -o d:\ -l server01
 2>&1

HyperVBackup.exe : Termine 'HyperVBackup.exe' non riconosciuto come nome di
cmdlet, funzione, programma eseguibile o file script. Controllare l'ortografia
del nome o verificare che il percorso sia incluso e corretto, quindi riprovare.
In riga:1 car:1
- HyperVBackup.exe --compressionlevel 2 -o d:\ -l server01 2>&1
- ~~~~~~~~~~~~~~~~
  - CategoryInfo          : ObjectNotFound: (HyperVBackup.exe:String) [], Co
    mmandNotFoundException
  - FullyQualifiedErrorId : CommandNotFoundException

Impossibile chiamare un metodo su un'espressione con valore null.
In C:\HVBackup\HVbackupLaunch.ps1:118 car:9
-     if ($elapsedTime.ToString().Length -gt 0)
-         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : InvalidOperation: (:) [], RuntimeException
  - FullyQualifiedErrorId : InvokeMethodOnNull

INFO    Successful Stop

**Comment by Jimshark** [comment]
Hi Donato,
You have to put: c:\HVBackup\ on the Path system variable so as the script to find the HyperVBackup.exe.
Hope that helps ! Cheers

**Comment by donatofurio** [comment]
ok, i did it and works! thanks.
ASAP i want to try to send report via gmail, there's some advices u can
give to me?

2016-05-04 7:10 GMT+02:00 Jimshark notifications@github.com:

> Hi Donato,
> You have to put: c:\HVBackup\ on the Path system variable so as the script
> to find the HyperVBackup.exe.
> Hope that helps ! Cheers
> 
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> https://github.com/nelsh/HVbackupLaunch/issues/1#issuecomment-216744148

## 

Donato Furio

___________________________________________________________________________________

DNA SERVIZI INFORMATICI SRL   VIA CADUTI DELLA LIBERTA',30  40043
MARZABOTTO (BO) TEL 051-6787143  FAX 051-6780154 WWW.DNASERVIZI.COM
http://www.dnaservizi.com/
___________________________________________________________________________________

Questo messaggio di posta elettronica contiene informazioni di carattere
confidenziale rivolte esclusivamente al destinatario sopra indicato. E'
vietato l'uso, la diffusione, distribuzione o riproduzione da parte di ogni
altra persona. Nel caso aveste ricevuto questo messaggio di posta
elettronica per errore, siete pregati di segnalarlo immediatamente al
mittente e distruggere quanto ricevuto (compresi i file allegati) senza
farne copia. Qualsivoglia utilizzo non autorizzato del contenuto di questo
messaggio costituisce violazione dell'obbligo di non prendere cognizione
della corrispondenza tra altri soggetti, salvo più grave illecito, ed
espone il responsabile alle relative conseguenze.

**Comment by Jimshark** [comment]
You have to use SSL Authentification to Pop and Smtp. And the associated ports. That's all i know about :-)

**Comment by nelsh** [comment]
Use HVbackupLaunch.ini (https://github.com/nelsh/HVbackupLaunch/blob/master/HVbackupLaunch.example.ini)

My ini-file:

```
LOGSTORETIME=30
KEEPBACKUPS=1
HVBACKUPEXE=c:/usr/HVBackup/HVBackup.exe --outputformat "{0}_{2:yyyyMMdd}.zip"
MAILADDRESS = Hyper-V Server <admin@example.com>
MAILSERVER  = smtp.mailgun.org:587
MAILUSER    = postmaster@mg.example.com
MAILPASSWORD    = fdg98kdj7bgdkj68cf6dfjkdf6dk
```
